-- Apply after the migration. Preserves existing edited place records.
insert into public.tbilisi_places (id, sort_order, content) values
('old-town', 0, '{"id": "old-town", "name": "Old Tbilisi", "category": "Old city", "image": "assets/city.jpg", "alt": "Historic buildings and balconies in Tbilisi", "short": "Follow winding lanes and carved wooden balconies.", "meta": "COBBLED LANES · EVERYDAY DISCOVERIES", "description": "Explore the historic streets around Meidan and the old city. Look up for wooden balconies, step into the smaller lanes, and discover the layers of architecture around the Mtkvari.", "note": "A good starting point for exploring on foot. Some lanes have steep slopes and uneven paving.", "lat": 41.6904, "lon": 44.8085, "source": "https://georgia.travel/popular-trips/a-short-tour-through-old-tbilisi"}'::jsonb),
('baths', 1, '{"id": "baths", "name": "Abanotubani", "category": "Old city", "image": "assets/baths.jpg", "alt": "Abanotubani sulfur bath district in Tbilisi", "short": "Brick bathhouse domes and the city’s warm beginnings.", "meta": "BATH DISTRICT · HISTORIC STREETS", "description": "Abanotubani is the historic sulfur bath district. Its domed bathhouses are a distinctive part of the old city, with the hot springs woven into the legend of Tbilisi’s founding.", "note": "Walking around the district is separate from booking a bath. Check individual bathhouses for appointments and prices.", "lat": 41.6879, "lon": 44.811, "source": "https://georgia.travel/abanotubani-in-tbilisi"}'::jsonb),
('bridge', 2, '{"id": "bridge", "name": "Bridge of Peace", "category": "Architecture", "image": "assets/bridge-new.jpg", "alt": "The glass and steel Bridge of Peace over the Mtkvari in Tbilisi", "short": "A contemporary crossing between the old city and Rike.", "meta": "RIVERSIDE · GLASS & STEEL", "description": "The pedestrian Bridge of Peace links the old city side of the river with Rike Park. Explore its modern form, then continue along the river for a different view of the historic skyline.", "note": "Combine the crossing with a stroll in Rike Park. The map marks the bridge.", "lat": 41.6933, "lon": 44.8086, "source": "https://georgia.travel/things-to-do-in-tbilisi"}'::jsonb),
('mtatsminda', 3, '{"id": "mtatsminda", "name": "Mtatsminda", "category": "Views & nature", "image": "assets/mtatsminda.jpg", "alt": "Bird sculptures and a tower at Mtatsminda Park", "short": "See the city unfold from the hills above the rooftops.", "meta": "HILLTOP · WIDE CITY VIEWS", "description": "Mtatsminda rises above Tbilisi and offers a different perspective on the city. Explore the park area and enjoy views across the neighborhoods and river.", "note": "Check current transport schedules before heading uphill.", "lat": 41.6946, "lon": 44.7867, "source": "https://georgia.travel/mtatsminda"}'::jsonb),
('rike', 4, '{"id": "rike", "name": "Rike Park", "category": "Views & nature", "image": "assets/rike.jpg", "alt": "Gardens and pathways in Rike Park, Tbilisi", "short": "Take a riverside pause beside the Bridge of Peace.", "meta": "GREEN SPACE · RIVER WALK", "description": "Rike Park sits beside the Mtkvari on the opposite bank from the old city. Use it as a pause between exploring the bridge and the surrounding streets.", "note": "The map marks the park area.", "lat": 41.6941, "lon": 44.8106, "source": "https://georgia.travel/things-to-do-in-tbilisi"}'::jsonb),
('metekhi', 5, '{"id": "metekhi", "name": "Metekhi riverbank", "category": "Architecture", "image": "assets/metekhi.jpg", "alt": "Metekhi church above the rocky Mtkvari riverbank", "short": "A historic church, a rocky bank, and a classic city view.", "meta": "HISTORIC LANDMARK · RIVER VIEWS", "description": "Metekhi church and the nearby equestrian monument of King Vakhtang Gorgasali stand above the rocky riverbank. The area looks across toward the old city and its hillside buildings.", "note": "The map marks Metekhi church; respect worshippers when visiting.", "lat": 41.69, "lon": 44.8113, "source": "https://georgia.travel/popular-trips/a-short-tour-through-old-tbilisi"}'::jsonb)
on conflict (id) do nothing;
